// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-A3AH4qG8frB2ltCMBO8_-xfYs8mxjE',
    appId: '1:523431703864:web:5afc594718a237662bbdcd',
    messagingSenderId: '523431703864',
    projectId: 'serenespace-6ff5c',
    authDomain: 'serenespace-6ff5c.firebaseapp.com',
    storageBucket: 'serenespace-6ff5c.appspot.com',
    measurementId: 'G-PLQMSSQ708',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzccRAYeHoNl71NV5-GMCM_K_j-v9FCg',
    appId: '1:523431703864:android:48d656b6d92a22ab2bbdcd',
    messagingSenderId: '523431703864',
    projectId: 'serenespace-6ff5c',
    storageBucket: 'serenespace-6ff5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKkcU9T73Wyg6DNRSpRL_NjsSYfioUbYE',
    appId: '1:523431703864:ios:2d679bf0f982bfe72bbdcd',
    messagingSenderId: '523431703864',
    projectId: 'serenespace-6ff5c',
    storageBucket: 'serenespace-6ff5c.appspot.com',
    iosBundleId: 'com.example.sereneSpaceFinal',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKkcU9T73Wyg6DNRSpRL_NjsSYfioUbYE',
    appId: '1:523431703864:ios:9a78d8a0b4dd128f2bbdcd',
    messagingSenderId: '523431703864',
    projectId: 'serenespace-6ff5c',
    storageBucket: 'serenespace-6ff5c.appspot.com',
    iosBundleId: 'com.example.sereneSpaceFinal.RunnerTests',
  );
}
